# Generated by Django 5.1.7 on 2025-04-17 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbvapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studentmodel',
            new_name='Student',
        ),
    ]
